### ISSUE TITLE
Samanage Extract Incidents

### ISSUE THREAD

**Issue by rbbayos** [cw2908/samanage-ruby#68]
Hi Chris W @cw2908,

Good Day!
May I ask if you have sample ruby scripts to extract incidents in Samanage with date coverage parameter?

Thank you in advance!
Regards,
Ron

**Comment by cw2908** [comment]
Hi @rbbayos 

I think something like this should work. This example saves all incidents created Dec 2018. This would run from the command `ruby script_filename.rb API_TOKEN` or `ruby script_filename.rb API_TOKEN eu` if on the EU datacenter.

```ruby
require 'samanage'
require 'csv'

api_token = ARGV[0]
input = ARGV[1]
datacenter = ARGV[2]
@samanage = Samanage::Api.new(token: api_token, datacenter: datacenter)
DEFAULT_FILENAME = "Incident Report #{DateTime.now.strftime("%b-%d-%Y-%l%M")}.csv"

#Simple CSV writer
def log_to_csv(row: , filename: DEFAULT_FILENAME, headers: OUTPUT_HEADERS)
  write_headers = !File.exists?(filename)
  CSV.open(filename, 'a+', write_headers: write_headers, force_quotes: true) do |csv| 
    csv << headers if csv.count.eql? 0
    csv << row
  end
end

#Save specific fields from incident and flatten to key pair
def format_incident(incident: )
  {
    id: incident.dig('id'),
    number: incident.dig('number'),
    name: incident.dig('name'),
    state: incident.dig('state'),
    assignee: incident.dig('assignee','name'), # I picked assignee->name because groups do not have an email
    requester: incident.dig('requester','email') # All requesters have email
  }
end


# Mimic filters from web app / UI filters. It could pull the dates from ARGV to make more dynamic - format just needs to be YYYY-MM-DD.
query_options = {
  'created[]' => 'Select Date Range',
  'created_custom_gte[]' => '2018-12-01',
  'created_custom_lte[]' => '2018-12-31',
  'layout' => 'long'
}

# Request and save incidents
@samanage.incidents(options: query_options).map do |incident|
  csv_data = format_incident(incident: incident)
  log_to_csv(row: csv_data.values, headers: csv_data.keys)
end
```

I only tried this in a test environment but let me know if it helps!

**Comment by rbbayos** [comment]
@cw2908 
It works... Thank you!

Also, I have questions with the other fields.
Assignee Reports_To
Custom Fields
Please see attached.

How I can include that in the extract? I'm having trouble referencing the correct syntax.? Thank you in advance!

![custom field1](https://user-images.githubusercontent.com/45483805/51455780-1f550700-1d86-11e9-863b-a2a1d01b2ac4.PNG)
![reports_to](https://user-images.githubusercontent.com/45483805/51455781-1f550700-1d86-11e9-9244-a5eb456a1354.PNG)
![fields](https://user-images.githubusercontent.com/45483805/51455805-3267d700-1d86-11e9-9fa6-b91ac0f5657f.PNG)

**Comment by cw2908** [comment]
Getting the reports to will be a little more complex because the system does not return the entire profile only the ID. It will need at least 1 additional query, possibly two to join the reports_to id to a group_id or the user_id.

To select custom fields from the json usually I do this: `incident.dig('custom_fields_values').select{|cf| cf['name'] == 'Some Field'}.first.to_h.dig('value')`

**Comment by rbbayos** [comment]
@cw2908 Thanks for this.
