### ISSUE TITLE
How to Filter ticket by Ticket State 

### ISSUE THREAD

**Issue by rbbayos** [cw2908/samanage-ruby#69]
Hi Chris, @cw2908 
How I can add another query to filter by State?
For example ticket CREATED from January 1, 2018 to current date AND
filter only tickets that with 'State' = 'Assigned', 'New','OnHold','Third Party' etc?  

AND another query to filter by ResolvedAT or ClosedAt
from January 1, 2018 to current date and State = 'Resolved' or 'Closed'

Thank you!

------------------
require 'samanage'
require 'csv'

# ruby script_name.rb API_TOKEN 2019-01-01 2019-12-31
api_token, start_date, end_date, datacenter = ARGV
@samanage = Samanage::Api.new(token: api_token, datacenter: datacenter)
DEFAULT_FILENAME = "Incident Report #{DateTime.now.strftime("%b-%d-%Y-%l%M")}.csv"

#Simple CSV writer
def log_to_csv(row: , filename: DEFAULT_FILENAME, headers: )
  write_headers = !File.exists?(filename)
  CSV.open(filename, 'a+', write_headers: write_headers, force_quotes: true, headers: headers) do |csv| 
    csv << row
  end
end

#Save specific fields from incident and flatten to key pair
def format_incident(incident: )
  {
    id: incident.dig('id'),
    number: incident.dig('number'),
    name: incident.dig('name'),
    state: incident.dig('state'),
    assignee: incident.dig('assignee','name'), # I picked assignee->name because groups do not have an email
    requester: incident.dig('requester','email'), # All requesters have email
	created_at: incident.dig('created_at'), # All requesters have email
	updated_at: incident.dig('updated_at'), # All requesters have email
	category: incident.dig('category','name'), # All requesters have email
	sucategory: incident.dig('category','name'), # All requesters have email
	siteid: incident.dig('site','id'), # All requesters have email
	sitename: incident.dig('site','name'), # All requesters have email
	sitelocation: incident.dig('site','location'), # All requesters have email
	reports_to: incident.dig('assignee','reports_to','id') # All requesters have email
  }
end

query_options = {
  'created[]' => 'Select Date Range',
  'created_custom_gte[]' => start_date,
  'created_custom_lte[]' => end_date,
  'layout' => 'long',
  
}

# Request and save incidents
@samanage.incidents(options: query_options).map do |incident|
  csv_data = format_incident(incident: incident)
  log_to_csv(row: csv_data.values, headers: csv_data.keys)
end

**Comment by cw2908** [comment]
There is no simple solution to this within the scope of this gem. States are filtered by ID and since there are custom states, these ids are unique to the account. Unfortunately I'm not aware of a way to query them in through API. 

The best way I've found to figure these out is by making the filter manually in the UI then URL decoding. This will result in a parameter you can add to the `query_option`s such as `'state[]' => 12345'`. This goes for any filter `'requested_by[]' => 999` etc.
